# Generated by Django 5.1.15 on 2026-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Måndag'), (1, 'Tisdag'), (2, 'Onsdag'), (3, 'Torsdag'), (4, 'Fredag'), (5, 'Lördag'), (6, 'Söndag')], unique=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Öppettid',
                'verbose_name_plural': 'Öppettider',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests_per_slot', models.PositiveIntegerField(default=20)),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30)),
                ('last_seating_buffer_minutes', models.PositiveIntegerField(default=60)),
                ('max_party_size', models.PositiveIntegerField(default=12)),
                ('booking_lead_minutes', models.PositiveIntegerField(default=60)),
                ('booking_horizon_days', models.PositiveIntegerField(default=90)),
                ('production_ready', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bokningsinställning',
                'verbose_name_plural': 'Bokningsinställningar',
            },
        ),
        migrations.CreateModel(
            name='SpecialClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Specialstängning',
                'verbose_name_plural': 'Specialstängningar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('party_size', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('special_request', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Bekräftad'), ('seated', 'Anländ'), ('cancelled', 'Avbokad'), ('no_show', 'Uteblev')], default='confirmed', max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ['date', 'time', 'created_at'],
                'indexes': [models.Index(fields=['date', 'time'], name='reservation_date_295b7b_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
            },
        ),
    ]
