FROM node:24-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1 \
    WATCHPACK_POLLING=true

COPY apps/web/package.json apps/web/package-lock.json* ./
COPY packages/api-client /app/packages/api-client
RUN npm install

COPY apps/web /app

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
