# Generated by Django 5.1.15 on 2026-09-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_featured_order_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='catalog_cat_parent_sort_idx'),
        ),
    ]
