# Generated by Django 5.1.15 on 2026-09-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_parent_and_sort_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'sort_order'], name='catalog_prod_cat_sort_idx'),
        ),
    ]
