# Generated by Django 5.1.15 on 2026-09-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_sort_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DagensLunchCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Dagens lunch · kategori',
                'verbose_name_plural': 'Dagens lunch · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='DagensLunchProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Dagens lunch · rätt',
                'verbose_name_plural': 'Dagens lunch · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='DryckCategory',
            fields=[
            ],
            options={
                'verbose_name': 'DRYCK · kategori',
                'verbose_name_plural': 'DRYCK · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='DryckProduct',
            fields=[
            ],
            options={
                'verbose_name': 'DRYCK · rätt',
                'verbose_name_plural': 'DRYCK · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='RivasMenyCategory',
            fields=[
            ],
            options={
                'verbose_name': 'RIVAS MENY · kategori',
                'verbose_name_plural': 'RIVAS MENY · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='RivasMenyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'RIVAS MENY · rätt',
                'verbose_name_plural': 'RIVAS MENY · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='SnacksDrinkarCategory',
            fields=[
            ],
            options={
                'verbose_name': 'SNACKS & DRINKAR · kategori',
                'verbose_name_plural': 'SNACKS & DRINKAR · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='SnacksDrinkarProduct',
            fields=[
            ],
            options={
                'verbose_name': 'SNACKS & DRINKAR · rätt',
                'verbose_name_plural': 'SNACKS & DRINKAR · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='StoraSallskapsmenyCategory',
            fields=[
            ],
            options={
                'verbose_name': 'STORA SÄLLSKAPSMENY · kategori',
                'verbose_name_plural': 'STORA SÄLLSKAPSMENY · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='StoraSallskapsmenyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'STORA SÄLLSKAPSMENY · rätt',
                'verbose_name_plural': 'STORA SÄLLSKAPSMENY · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='TakeAwayCategory',
            fields=[
            ],
            options={
                'verbose_name': 'TAKE AWAY · kategori',
                'verbose_name_plural': 'TAKE AWAY · kategorier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='TakeAwayProduct',
            fields=[
            ],
            options={
                'verbose_name': 'TAKE AWAY · rätt',
                'verbose_name_plural': 'TAKE AWAY · rätter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
