# Generated by Django 5.1.15 on 2026-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_inquiries_news_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='offers/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Erbjudande',
                'verbose_name_plural': 'Erbjudanden',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Riva Bistro', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Goda smaker, äkta upplevelser', max_length=200)),
                ('street', models.CharField(blank=True, default='Hornsbergs Strand 57', max_length=200)),
                ('postal_code', models.CharField(blank=True, default='112 16', max_length=20)),
                ('city', models.CharField(blank=True, default='Stockholm', max_length=80)),
                ('country', models.CharField(blank=True, default='SE', max_length=2)),
                ('area', models.CharField(blank=True, default='Kungsholmen', max_length=80)),
                ('phone', models.CharField(blank=True, default='087042050', max_length=40)),
                ('phone_e164', models.CharField(blank=True, default='+4687042050', max_length=40)),
                ('email', models.EmailField(blank=True, default='info@rivabistro.se', max_length=254)),
                ('map_url', models.URLField(blank=True, default='https://www.google.com/maps/search/?api=1&query=Hornsbergs+Strand+57+112+16+Stockholm')),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com/rivabistro')),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com/rivabistro')),
                ('social_verified', models.BooleanField(default=False)),
                ('kitchen_hours', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurangprofil',
                'verbose_name_plural': 'Restaurangprofil',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Goda smaker, äkta upplevelser', max_length=200)),
                ('hero_body', models.TextField(blank=True, default='Medelhavsinspirerad mat på Kungsholmen — lunch, middag och privata tillställningar vid vattnet.')),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='site/')),
                ('hero_image_url', models.CharField(blank=True, default='/scenes/hero-food.jpg', max_length=500)),
                ('primary_cta_label', models.CharField(default='Boka bord', max_length=80)),
                ('primary_cta_href', models.CharField(default='/boka', max_length=200)),
                ('secondary_cta_label', models.CharField(default='Se menyn', max_length=80)),
                ('secondary_cta_href', models.CharField(default='/meny', max_length=200)),
                ('about_title', models.CharField(default='Välkommen till Riva', max_length=200)),
                ('about_body', models.TextField(blank=True, default='Vi lagar mat med råvaror i säsong, generösa portioner och en avslappnad stämning vid Hornsbergs Strand.')),
                ('about_image', models.FileField(blank=True, null=True, upload_to='site/')),
                ('about_image_url', models.CharField(blank=True, default='/scenes/home-interior.jpg', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Startsida',
                'verbose_name_plural': 'Startsida',
            },
        ),
    ]
