/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sets the csrftoken cookie so the admin client can send X-CSRFToken. */
        get: operations["admin_auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the current admin session state (200 always, client-friendly). */
        get: operations["admin_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/closures/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_closures_list"];
        put?: never;
        post: operations["admin_closures_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/closures/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["admin_closures_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hours/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_hours_list"];
        put: operations["admin_hours_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_menu_categories_list"];
        put?: never;
        post: operations["admin_menu_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_menu_categories_retrieve"];
        put: operations["admin_menu_categories_update"];
        post?: never;
        delete: operations["admin_menu_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_menu_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/menu/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_menu_products_list"];
        put?: never;
        post: operations["admin_menu_products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_menu_products_retrieve"];
        put: operations["admin_menu_products_update"];
        post?: never;
        delete: operations["admin_menu_products_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_menu_products_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/menu/products/{id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_menu_products_image_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_overview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_reservations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_reservations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["admin_reservations_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["admin_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/contact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public contact form → emails the restaurant notification inbox. */
        post: operations["contact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/inquiry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public private-events inquiry → emails the restaurant notification inbox. */
        post: operations["events_inquiry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Reports API and database readiness for local Docker healthchecks.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hours/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public opening hours for footer / booking display. */
        get: operations["hours_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["menu_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/featured/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Featured dishes for the homepage (admin-managed). */
        get: operations["menu_featured_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["menu_products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/products/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["menu_products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create a real, confirmed reservation (backend-enforced availability).
         *
         *     Public endpoint: no session auth (and therefore no CSRF), so it works for
         *     anonymous guests even if a Django session happens to be authenticated.
         */
        post: operations["reservations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public availability for a given date: open slots with remaining capacity. */
        get: operations["reservations_availability_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminCategory: {
            readonly id: number;
            name: string;
            readonly slug: string;
            description?: string;
            sort_order?: number;
            is_active?: boolean;
            readonly product_count: number;
        };
        AdminOverview: {
            today_count: number;
            today_guests: number;
            upcoming_count: number;
            production_ready: boolean;
            max_guests_per_slot: number;
            todays_reservations: components["schemas"]["Reservation"][];
        };
        AdminProduct: {
            readonly id: number;
            category: number;
            readonly category_name: string;
            name: string;
            readonly slug: string;
            description?: string;
            /** Format: decimal */
            base_price: string;
            /** Format: decimal */
            vat_rate?: string;
            /** Format: uri */
            image_url?: string;
            readonly image_upload_url: string;
            is_available?: boolean;
            is_featured?: boolean;
            featured_order?: number;
            sort_order?: number;
        };
        AdminSession: {
            authenticated: boolean;
            username?: string;
            is_staff?: boolean;
        };
        Availability: {
            date: string;
            enabled: boolean;
            closed: boolean;
            max_party_size: number;
            /** Booking horizon in days (inclusive). */
            horizon_days?: number;
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        AvailabilitySlot: {
            time: string;
            remaining: number;
            available: boolean;
        };
        Category: {
            readonly id: number;
            name: string;
            slug: string;
            description?: string;
            readonly product_count: number;
        };
        Contact: {
            name: string;
            /** Format: email */
            email: string;
            /** @default  */
            phone: string;
            /** @default  */
            subject: string;
            message: string;
        };
        DetailResponse: {
            detail: string;
        };
        EventInquiry: {
            name: string;
            /** Format: email */
            email: string;
            /** @default  */
            phone: string;
            /** @default  */
            event_type: string;
            /** @default  */
            guests: string;
            /** @default  */
            date: string;
            message: string;
        };
        Login: {
            username: string;
            password: string;
        };
        ModifierGroup: {
            readonly id: number;
            name: string;
            min_selections?: number;
            max_selections?: number;
            required?: boolean;
            readonly options: components["schemas"]["ModifierOption"][];
        };
        ModifierOption: {
            readonly id: number;
            name: string;
            /** Format: decimal */
            price_delta?: string;
            is_available?: boolean;
            readonly pricing: components["schemas"]["Pricing"];
        };
        OpeningHours: {
            weekday: components["schemas"]["WeekdayEnum"];
            readonly weekday_label: string;
            /** Format: time */
            opens_at?: string | null;
            /** Format: time */
            closes_at?: string | null;
            is_closed?: boolean;
        };
        PatchedAdminCategory: {
            readonly id?: number;
            name?: string;
            readonly slug?: string;
            description?: string;
            sort_order?: number;
            is_active?: boolean;
            readonly product_count?: number;
        };
        PatchedAdminProduct: {
            readonly id?: number;
            category?: number;
            readonly category_name?: string;
            name?: string;
            readonly slug?: string;
            description?: string;
            /** Format: decimal */
            base_price?: string;
            /** Format: decimal */
            vat_rate?: string;
            /** Format: uri */
            image_url?: string;
            readonly image_upload_url?: string;
            is_available?: boolean;
            is_featured?: boolean;
            featured_order?: number;
            sort_order?: number;
        };
        PatchedReservationSettings: {
            max_guests_per_slot?: number;
            slot_interval_minutes?: number;
            last_seating_buffer_minutes?: number;
            max_party_size?: number;
            booking_lead_minutes?: number;
            booking_horizon_days?: number;
            production_ready?: boolean;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedReservationStatus: {
            status?: components["schemas"]["StatusEnum"];
        };
        Pricing: {
            price_ex_vat: string;
            vat_amount: string;
            price_inc_vat: string;
            vat_rate: string;
        };
        ProductDetail: {
            readonly id: number;
            name: string;
            slug: string;
            description?: string;
            /**
             * @description Prefer an uploaded image over an external URL.
             *
             *     Uploaded images are returned as a root-relative media path (e.g.
             *     /media/menu/x.webp). The frontend resolves it against the public API
             *     origin, which works for both SSR and browser (unlike an absolute URL
             *     built from the internal container host).
             */
            readonly image_url: string;
            is_available?: boolean;
            is_featured?: boolean;
            readonly category_name: string;
            readonly category_slug: string;
            readonly pricing: components["schemas"]["Pricing"];
            readonly modifier_groups: components["schemas"]["ModifierGroup"][];
            inventory_count?: number;
        };
        ProductList: {
            readonly id: number;
            name: string;
            slug: string;
            description?: string;
            /**
             * @description Prefer an uploaded image over an external URL.
             *
             *     Uploaded images are returned as a root-relative media path (e.g.
             *     /media/menu/x.webp). The frontend resolves it against the public API
             *     origin, which works for both SSR and browser (unlike an absolute URL
             *     built from the internal container host).
             */
            readonly image_url: string;
            is_available?: boolean;
            is_featured?: boolean;
            readonly category_name: string;
            readonly category_slug: string;
            readonly pricing: components["schemas"]["Pricing"];
        };
        Reservation: {
            readonly id: number;
            readonly ref: string;
            readonly name: string;
            readonly phone: string;
            /** Format: email */
            readonly email: string;
            readonly party_size: number;
            /** Format: date */
            readonly date: string;
            /** Format: time */
            readonly time: string;
            readonly special_request: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_label: string;
            readonly confirmation_email_sent: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        ReservationCreate: {
            name: string;
            phone: string;
            /** Format: email */
            email: string;
            party_size: number;
            /** Format: date */
            date: string;
            /** Format: time */
            time: string;
            /** @default  */
            special_request: string;
        };
        ReservationCreateResponse: {
            readonly id: number;
            readonly ref: string;
            readonly name: string;
            readonly phone: string;
            /** Format: email */
            readonly email: string;
            readonly party_size: number;
            /** Format: date */
            readonly date: string;
            /** Format: time */
            readonly time: string;
            readonly special_request: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_label: string;
            readonly confirmation_email_sent: boolean;
            /** Format: date-time */
            readonly created_at: string;
            readonly email_sent: boolean;
        };
        ReservationSettings: {
            max_guests_per_slot?: number;
            slot_interval_minutes?: number;
            last_seating_buffer_minutes?: number;
            max_party_size?: number;
            booking_lead_minutes?: number;
            booking_horizon_days?: number;
            production_ready?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        SpecialClosure: {
            readonly id: number;
            /** Format: date */
            date: string;
            reason?: string;
        };
        /**
         * @description * `confirmed` - Bekräftad
         *     * `seated` - Anländ
         *     * `cancelled` - Avbokad
         *     * `no_show` - Uteblev
         * @enum {string}
         */
        StatusEnum: "confirmed" | "seated" | "cancelled" | "no_show";
        StatusResponse: {
            status: string;
        };
        /**
         * @description * `0` - Måndag
         *     * `1` - Tisdag
         *     * `2` - Onsdag
         *     * `3` - Torsdag
         *     * `4` - Fredag
         *     * `5` - Lördag
         *     * `6` - Söndag
         * @enum {integer}
         */
        WeekdayEnum: 0 | 1 | 2 | 3 | 4 | 5 | 6;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    admin_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
        };
    };
    admin_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
        };
    };
    admin_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
        };
    };
    admin_closures_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialClosure"][];
                };
            };
        };
    };
    admin_closures_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialClosure"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialClosure"];
                };
            };
        };
    };
    admin_closures_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_hours_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningHours"][];
                };
            };
        };
    };
    admin_hours_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningHours"][];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningHours"][];
                };
            };
        };
    };
    admin_menu_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"][];
                };
            };
        };
    };
    admin_menu_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCategory"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
        };
    };
    admin_menu_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
        };
    };
    admin_menu_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
        };
    };
    admin_menu_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_menu_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
        };
    };
    admin_menu_products_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"][];
                };
            };
        };
    };
    admin_menu_products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProduct"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_menu_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_menu_products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProduct"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_menu_products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_menu_products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminProduct"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_menu_products_image_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    image: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_overview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverview"];
                };
            };
        };
    };
    admin_reservations_list: {
        parameters: {
            query?: {
                date?: string;
                q?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    admin_reservations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    admin_reservations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedReservationStatus"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    admin_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationSettings"];
                };
            };
        };
    };
    admin_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedReservationSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationSettings"];
                };
            };
        };
    };
    contact_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contact"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    events_inquiry_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventInquiry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example riva-bistro-backend */
                        service?: string;
                        /** @example ok */
                        database?: string;
                    };
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example degraded */
                        status?: string;
                        service?: string;
                        /** @example unavailable */
                        database?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    hours_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningHours"][];
                };
            };
        };
    };
    menu_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    menu_featured_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"][];
                };
            };
        };
    };
    menu_products_list: {
        parameters: {
            query?: {
                category?: string;
                featured?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"][];
                };
            };
        };
    };
    menu_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
        };
    };
    reservations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationCreateResponse"];
                };
            };
        };
    };
    reservations_availability_retrieve: {
        parameters: {
            query: {
                /** @description ISO date (YYYY-MM-DD) */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
        };
    };
}
